### ISSUE TITLE
Doesnt show info for CTs

### ISSUE THREAD

**Issue by wayLANder3** [Czar-VG/RetakeSiteHud#1]
Show ifno "Plant the bomb" for Ts aswell, but for CTs there is no hud info.

**Comment by Xenoadria** [comment]
Can confirm. However for me, (tested with friend meaning 2 of us were on server) when I am T side I get message "Plant the bomb" on CT side I get nothing and my friend gets info on both sides.

I have the latest Metamod and Sourcemod.

**Comment by Czar-VG** [comment]
Try the version I just uploaded

**Comment by Xenoadria** [comment]
Everything works with the latest version. Thanks !
