### ISSUE TITLE
GetClientTeam

### ISSUE THREAD

**Issue by busheezy** [Czar-VG/RetakeSiteHud#5]
Hello, I'm using 1.4 but I think your current code still has the same problem.

Is there any reason you can't move your GetClientTeam() call to be inside your IsValidClient call? I'm getting errors.

```
L 11/02/2018 - 15:52:37: [SM] Exception reported: Client 3 is not in game
L 11/02/2018 - 15:52:37: [SM] Blaming: retakehud.smx
L 11/02/2018 - 15:52:37: [SM] Call stack trace:
L 11/02/2018 - 15:52:37: [SM]   [0] GetClientTeam
L 11/02/2018 - 15:52:37: [SM]   [1] Line 73, plugin.sp::displayHud
```

**Comment by b3none** [comment]
Shit dude, that's my bad. I'll put in a PR with the change.
